### ISSUE TITLE
can't use for new version

### ISSUE THREAD

**Issue by max-gui** [savantly-net/log4j2-extended-jsonlayout#2]
<dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.9.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.9.1</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.8.7</version>
    </dependency>
</dependency>

errors:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.core.layout.JacksonFactory$JSON.<init>(ZZ)V
	at org.apache.logging.log4j.core.layout.ExtendedJsonLayout.getObjectWriter(ExtendedJsonLayout.java:371)
	at org.apache.logging.log4j.core.layout.ExtendedJsonLayout.<init>(ExtendedJsonLayout.java:352)
	at org.apache.logging.log4j.core.layout.ExtendedJsonLayout$Builder.build(ExtendedJsonLayout.java:282)
	at org.apache.logging.log4j.core.layout.ExtendedJsonLayout$Builder.build(ExtendedJsonLayout.java:253)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
	at logs.<clinit>(logs.java:10)

**Comment by NunoCardia** [comment]
Any news regarding this issue?

**Comment by tomilaurell** [comment]
I have forked this and I will continue to maintain it:
https://github.com/tomilaurell/log4j2-extended-jsonlayout

**Comment by jdbranham** [comment]
Sorry for the hiatus - 
log4j2-extended-jsonlayout has a dependency on Jackson v2.8.7, but log4j2 v2.9.0 updated to Jackson v2.9.0

You can exclude Jackson from log4j2-extended-jsonlayout, or add Jackson v2.9.0 as a dependency in your project to avoid this error.

I'll update the version number to match the Log4j2 versions, so compatibility by version will be implied.

More details - 
https://issues.apache.org/jira/browse/LOG4J2-2017

**Comment by tomilaurell** [comment]
I can create a PR for that within couple of days.

**Comment by tomilaurell** [comment]
@jdbranham
Could you add me basic write access to create feature branches? Now I cannot push my PR.

**Comment by jdbranham** [comment]
Thanks @tomilaurell 
It looks like your repo is not actually a fork of this repo. 
[not listed here]
https://github.com/savantly-net/log4j2-extended-jsonlayout/network/members   

I like to merge a couple PRs from someone at least, before giving write access to the repo. Can you create a real fork of this repository?

**Comment by tomilaurell** [comment]
I'll do proper fork. I don't have time now, but within a month its there.

**Comment by jdbranham** [comment]
Snapshot version of 2.9 support is available -
```
<dependency>
	<groupId>net.savantly.log4j2</groupId>
	<artifactId>extended-jsonlayout</artifactId>
	<version>2.9.0-SNAPSHOT</version>
</dependency>
```

If you're using a SNAPSHOT, add the sonatype snapshot repository to your pom.

```
<repositories>
  <repository>
    <id>oss.sonatype.org-snapshot</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```
